version: "3.8"

services:
  app:
    build: .
    container_name: folyod-app
    restart: unless-stopped
    depends_on:
      - sql
      - nosql
    links:
      - sql:sql
      - nosql:nosql
    volumes:
    - ../:/var/www/html
#    - ../laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
    command: >
      bash -c "/usr/bin/supervisord -n"

  web:
    image: nginx:1.21
    container_name: folyod-nginx
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8014:80"

#  node:
#    image: node
#    container_name: folyod-node
#    working_dir: /home/node/app
#    restart: unless-stopped
#    volumes:
#      - ../:/home/node/app
#    networks:
#      - default

  sql:
    image: postgres:14
    container_name: folyod-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: folyod
    restart: unless-stopped
    volumes:
      - folyod-pgsql:/var/lib/postgresql/data
    ports:
        - "8015:5432"

  nosql:
    image: redis:6
    container_name: folyod-redis
    restart: unless-stopped
    ports:
      - "8016:6379"

volumes:
  folyod-pgsql: