openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https://localhost:8014/api'
paths:
  /learners:
    $ref: '/resources/public/resources/createLearner.yaml'

  /login:
    post:
      requestBody:
        content:
          'application/json':
            schema:
              properties:
                email:
                  type: string
                  example: 'test@email.ru'
                password:
                  type: string
                  example: 'password'
              required:
                - email
                - password
      responses:
        200:
          description: 'Аутентификация ученика'
          content:
            'application/json':
              schema:
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        token:
                          type: string
                          example: '1|aEgm6UONPERmhBHRiMdnRsFy5tml7bRzlMzYmlPM'

